### ISSUE TITLE
XRay version >3 URL?

### ISSUE THREAD

**Issue by Smasherr** [jfrog/jfrog-idea-plugin#118]
It's not clear from the documentation what URL I should specify to connect to XRay. Since version 3, XRay fully integrates into Artifactory so there is no more separate URL for XRay. When I'm specifying the URL of Artifactory I am getting the following error message:

![image](https://user-images.githubusercontent.com/10698205/115873826-b583a600-a443-11eb-892f-49e8836cd561.png)

I checked the connection with the Wireshark and found out the plugin tries to access the URL `https://[MASKED]/artifactory/api/v1/system/version` but this endpoint is available without `v1` at `https://[MASKED]/artifactory/api/system/version`. Is this an incompatibility with XRay >= 3 or am I setting the wrong URL?

**Comment by yahavi** [comment]
Thanks for your feedback, @Smasherr.

The Artifactory and Xray API URL are a bit different. The Xray API URL ends by `/xray`:
Artifactory API URL is:
`https://<jfrog-platform-url>/artifactory`
Xray API URL is:
`https://<jfrog-platform-url>/xray`

In the next version we are going to allow providing the JFrog platform URL and by this way, hopefully, prevent the confusion.
See https://github.com/jfrog/jfrog-idea-plugin/pull/103 for more info.

Please let me know if it helped.

**Comment by Smasherr** [comment]
Thank you for the quick response! `https://<jfrog-platform-url>/xray` works!
