### ISSUE TITLE
Plugin scan consumes max IntelliJ memory and doesn't complete (Go)

### ISSUE THREAD

**Issue by shayshim** [jfrog/jfrog-idea-plugin#140]
**Describe the bug**
I have Go project which I would like to scan. 
Xray scan seems to be running, but does not complete. 
It always uses the max memory configured in IntelliJ, even if I give it 16GB. 

**To Reproduce**
1. Replace relative paths with absolute paths in the go.mod files (workaround for another bug in the plugin, which doesn't work using relative paths: https://github.com/jfrog/jfrog-idea-plugin/issues/139)
2. Scan will automatically start and get stuck using all max given memory

**Expected behavior**
Scan completes and using some limit of the available memory.

**Versions**
- JFrog IDEA plugin version: 1.9.1
- Operating system: macOS 11.4
- Xray version: 3.27.2

**Comment by eyalbe4** [comment]
Thanks so much for reporting this issue @shayshim!
We're currently working on reducing the memory used by the plugin.
We'll keep this issue up to date with our progress.

**Comment by yahavi** [comment]
Fixed in 1.10.1.
