### ISSUE TITLE
Xray Scan Produces No Results.2

### ISSUE THREAD

**Issue by xslicex** [jfrog/jfrog-idea-plugin#145]
**Describe the bug**
This issue is very similar to the one described at https://github.com/jfrog/jfrog-idea-plugin/issues/97
The difference is that it looks like maven project is loaded properly (pom.xml has no compilation errors, JDK is available and maven dependency tree is shown properly in the maven tab), indexing is done, something is performed in the background, but after scanning nothing is shown in the JFrog tab.

What else could be the problem?
It looks like the plugin works except showing the result.

**Versions**
X-ray: Cloud version, 3.33.1 (but tried with 3.32.2 as well)
JForg IDEA Plugin version: 1.9.2
OS: Windows 10 Pro
IDE:
IntelliJ IDEA 2021.2.1 (Community Edition)
Build #IC-212.5080.55, built on August 24, 2021
Runtime version: 11.0.11+9-b1504.16 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2028M
Cores: 4
Non-Bundled Plugins: idea.plugin.protoeditor (212.5080.8), CheckStyle-IDEA (5.56.0), Docker (212.5080.8), org.jetbrains.kotlin (212-1.5.30-release-409-IJ4638.7), org.jfrog.idea (1.9.2), com.haulmont.jpab (5.4-212), org.mapstruct.intellij (1.3.0)
Kotlin: 212-1.5.30-release-409-IJ4638.7

**To Reproduce**
Install the JFrog Xray plugin from the Marketplace
Restart IntelliJ
Configure JFrog Xray connection
Open an existing Java/Maven project
Click the "Refresh Scan" icon in the JFrog pane

**Expected behavior**
Detailed list of components with an icon indicating issue severities are shown in the JFrog tab.

**Screenshots**
N/A

**Additional context**
I also tried with an npm project, with similar result - looks like it performs the scan, yet no result is shown.

In the event log tab I only see INFO messages that some of the folders are excluded due to the defined Excluded Paths pattern.
I checked the IDEA log, where the only suspicious message was:
2021-09-21 08:09:37,604 [  68772]   WARN - nSystem.impl.ActionToolbarImpl - 'JFrog toolbar' toolbar by default uses any focused component to update its actions. Toolbar actions that need local UI context would be incorrectly disabled. Please call toolbar.setTargetComponent() explicitly.

**Comment by yahavi** [comment]
@xslicex,
Thanks for reporting this issue.
We couldn't reproduce it in our environment. However, in https://github.com/jfrog/jfrog-idea-plugin/pull/148 we made a change that may hopefully resolve this issue.

The change is included in the latest JFrog IDEA plugin 1.10.1. Feel free to upgrade.
We'd appreciate your feedback on that.

**Comment by xslicex** [comment]
Hi @yahavi !
I upgraded the JFrog IDEA plugin to v1.10.1 and now it works!
So your change did solve my issue.
Thanks!
--slice
