### ISSUE TITLE
Soft refresh in a maven project does not respond to pom.xml changes

### ISSUE THREAD

**Issue by gitta-jfrog** [jfrog/jfrog-idea-plugin#182]
**Describe the bug**
Changing fields (GroupID, Version for example) in the pom.xml of a maven project should trigger a soft refresh of the project dependency tree but nothing happened. Refresh of the project dependency tree is possible by reloading maven project or reopening the project.

**To Reproduce**
1. Clone and open https://github.com/jfrog/project-examples/tree/master/maven-examples/maven-example.
2. The project's dependency tree appears in the project view.
3. Change the version in the pom.xml of the root module.
4. No changes in the dependency tree, the old version still appears in the dependency tree.
5. No changes when clicking on the "refresh scan" button as well.

**Expected behavior**
The dependency tree should be updated according to the changes in the pom.xml 

**Screenshots**
![image](https://user-images.githubusercontent.com/69511528/146680449-117acb48-49b7-41ce-ac3e-7a166a9f9e29.png)

**Versions**

- JFrog IDEA plugin version: 1.12.0
- Operating system: macOS Big Sur 11.4
- IDEA version: 2021.3

**Comment by yahavi** [comment]
@gitta-jfrog,
Thanks for reporting this issue.
The JFrog IDEA plugin pulls the dependencies information from the bundled IDEA Maven plugin. 
To enable this feature, please allow automatically reloading a Maven project by IntelliJ:

In the side Maven panel, click on the `Configuration | Auto-Reload Settings...`:
<img width="612" alt="image" src="https://user-images.githubusercontent.com/11367982/146926518-bdd1df9a-7694-4134-a809-24ce601054a2.png">

And then choose `Any change`:
<img width="980" alt="image" src="https://user-images.githubusercontent.com/11367982/146926416-8f0862ef-fa2e-4e01-b48a-59b8ceceaa09.png">

For more information about this configuration see:
https://www.jetbrains.com/help/idea/settings-build-tools.html
