### ISSUE TITLE
No function on rightclick on vulnerability

### ISSUE THREAD

**Issue by 8L4ckc0FF33** [jfrog/jfrog-idea-plugin#231]
**Describe the bug**
In https://www.jfrog.com/confluence/display/JFROG/JFrog+IntelliJ+IDEA+Plugin is stated, that it should be possible to rightclick packages or vulnerabilities to show in project descriptor, exclude dependency or create ignore rule. Neither of this is possible. A rightclick does not offer any functionality

**To Reproduce**
I am using Intellij Idea 2022.2.2 (Ultimate Edition). Jfrog Plugin 1.16.1 and Artifactory 7.41.13

**Expected behavior**
As described in https://www.jfrog.com/confluence/display/JFROG/JFrog+IntelliJ+IDEA+Plugin

**Versions**
- JFrog IDEA plugin version: 1.16.1
- Operating system: Windows 
- Xray version: 3.57.6

**Comment by yahavi** [comment]
@8L4ckc0FF33,
Thanks for reporting this issue!
We created #233 to fix the missing "Show in depepdendency tree" button issue. We'll keep you updated on that.

**Workaround:**
Manually open the project descriptor (pom.xml, package.lock, etc) after an Xray scan is completed.

**Ignore Rules:**
Ignore Rules can only be created when a [Project](https://www.jfrog.com/confluence/display/JFROG/Projects) or an [Xray Watch](https://www.jfrog.com/confluence/display/JFROG/Configuring+Xray+Watches) is provided. When a violation exists, you can right-click on the **violation** in the vulnerabilities table to create an ignore rule.
For example:
**Step 1** - Select an Xray Watch:
![image](https://user-images.githubusercontent.com/11367982/197334086-600c84be-9f78-4d97-a6e8-d2e420b66156.png)
**Step 2** - Right click on the **violation** to create the Ignore Rule:
![image](https://user-images.githubusercontent.com/11367982/197334106-6d4f6e69-b1a3-4632-a61b-f4b1c2d30c09.png)
Please let us know if you need assistance with creating a Project or Xray Watches.

**Comment by 8L4ckc0FF33** [comment]
I tried, but unfortunately when trying to do so I get
```
"**Cannot Save Settings**
Illegal characters in watch <x>.<y>.<z>"
```
That's bad, since all my watches follow the dotted-pattern. Why does the plugin not accept the same characters as Xray? In that case I'd like to file a feature request since it's really a lot of work to change my watches from a dotted to a dashed pattern.

I also created a watch to check your suggestion but nothing happens. Although i selected a watch and rescanned my program no rightclick action was possible.

**Comment by yahavi** [comment]
Thanks for the feedback, @8L4ckc0FF33!
We created https://github.com/jfrog/jfrog-idea-plugin/pull/234 to fix the issue of watches with `.`.
We'll keep you updated.

**Comment by 8L4ckc0FF33** [comment]
Thank you very much @yahavi

**Comment by yahavi** [comment]
@8L4ckc0FF33,
JFrog IDEA plugin 1.16.2 is released. This version should include a fix for this issue.
Feel free to upgrade - we'd appreciate your feedback on that.
