### ISSUE TITLE
No vulnerabilities shown in "mixed" projects?

### ISSUE THREAD

**Issue by 8L4ckc0FF33** [jfrog/jfrog-idea-plugin#232]
Hi there,
we have some Gradle projects, which are built with a Spring Java backend and a Vue JS Frontend. Both are built by one Gradle file. The rough structure is like that
```
project
-src/ (backend)
--main/
--test/
-vueapp/
--src/
--tests/
--package.json
-package.json
-build.gradle

```
Unfortunately no vulnerability information is shown as described in the package.json as described in the screencast https://www.jfrog.com/confluence/display/JFROG/JFrog+IntelliJ+IDEA+Plugin

 I am using Intellij Idea 2022.2.2 (Ultimate Edition). Jfrog Plugin 1.16.1 and Artifactory 7.41.13

How can I manage to scan such projects for vulnerabilities?

Btw.: Vulnerabilities of this project are also not shown in the Xray UI. Is this not supported by Xray? Is or will it be possible to scan vulnerabilities of an artifact by simply providing an SBOM?

**Comment by yahavi** [comment]
@8L4ckc0FF33,
Thanks for using the JFrog IDEA plugin.

You should see the dependency tree even if you don't have vulnerabilities or violations.
Could you please provide more information about your environment? 
* Do you have a JFrog environment configured? Does the "Test connection" button work for you?
* What do you see after clicking on the Refresh button? ![image](https://user-images.githubusercontent.com/11367982/197334398-f543ca33-7a56-443d-bc57-42cb46432674.png)
* Could you please share here the Notifications log?

**Comment by 8L4ckc0FF33** [comment]
* Yes, I have a local JFrog environment configured. The "Test connection" buttons works for me.
* When clicking the refresh-button i see a list of affected dependencies and its vulnerabilities. But i cannot see them when looking at the package.json. Once during the scan, there was a green checkmark in the gradle file, but after the scan completed it was gone. 
* Where do i get the notifications log?

**Comment by yahavi** [comment]
Thanks for the input, @8L4ckc0FF33,

> When clicking the refresh-button i see a list of affected dependencies and its vulnerabilities. But i cannot see them when looking at the package.json. Once during the scan, there was a green checkmark in the gradle file, but after the scan completed it was gone.

Since you see a complete dependency tree with vulnerabilities, I believe this issue should be resolved by https://github.com/jfrog/jfrog-idea-plugin/pull/233.

**Comment by 8L4ckc0FF33** [comment]
> The NavigationService gets populated after the code inspection. Code inspections may run after one of the 3 following options:
> 1. The project descriptor (like pom.xml) was opened.
I opened a package.json and a build.gradle file but neither showed me a hint like a checkmark whether the packages was analysed. 
> 2. The user manually triggered code inspection by clicking on "Code | Inspect Code" - we intentionally skip our code inspections in this case (see https://github.com/jfrog/jfrog-idea-plugin/pull/186).
I triggered the inspection but it didn't change.

> 3. An Xray scan was completed - we accidentally skip code inspections in this case.
I guess this is made when I startup IDEA? So in that case nothing changed either.

I expect something like that:

![grafik](https://user-images.githubusercontent.com/55756010/198300143-24f5fe51-6b60-47ae-8fbc-397fbfef9ae1.png)

**Comment by yahavi** [comment]
@8L4ckc0FF33,
JFrog IDEA plugin 1.16.2 is released. This version should include a fix for this issue.
Feel free to upgrade - we'd appreciate your feedback on that.
