### ISSUE TITLE
NullPointerException when SeverityReasons are missing from vulnerability

### ISSUE THREAD

**Issue by jorander** [jfrog/jfrog-idea-plugin#323]
**Describe the bug**
The plug-in throws NullPointerException when trying to show information for a vulnerability that does not have any severity reason data.

`java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because the return value of "com.jfrog.ide.common.nodes.subentities.ResearchInfo.getSeverityReasons()" is null
	at com.jfrog.ide.idea.ui.webview.WebviewObjectConverter.convertIssueToDepPage(WebviewObjectConverter.java:19)
	at com.jfrog.ide.idea.ui.JFrogLocalToolWindow.updateIssueOrLicenseInWebview(JFrogLocalToolWindow.java:247)
	at com.jfrog.ide.idea.ui.JFrogLocalToolWindow.lambda$registerListeners$1(JFrogLocalToolWindow.java:124)
	...`

**To Reproduce**
Scan a codebase with a vulnerability that does not have any serverity reason data, e.g. XRAY-199921.
Click the vulnerabiltity in the tree-view.

**Expected behavior**
Missing data is handled and vulnerability information rendered.

**Screenshots**
N/A

**Versions**
- JFrog IDEA plugin version: 2.1.2
- Operating system: RHEL 8.7
- Xray version: 7.49.3

**Additional context**
N/A

**Comment by yahavi** [comment]
@jorander 
Thanks for using the JFrog IDEA plugin.
We merged https://github.com/jfrog/jfrog-idea-plugin/pull/324 to fix this issue.
We'll let you know once the new version is released.
