### ISSUE TITLE
Unable to Copy Text from Plugin Info Screens

### ISSUE THREAD

**Issue by ranma2913** [jfrog/jfrog-idea-plugin#357]
**Describe the bug**
After a recent update I installed I'm no longer able to copy text from the plugin. I need this feature to mention fixes in Commit Messages, chats with peers, and web searching. Typing CVE Codes and descriptions by hand is a drag!

**To Reproduce**

1. Install latest IntelliJ & Xray Plugin. 
2. Scan a project with vulnerability
3. Try and copy the CVSS ID from the plugin window.

**Expected behavior**
I should be able to highlight text in the plugin window and be able to copy using both:

1. Control/Command + C
2. Right-Click menu Copy
3. OR maybe just add a COPY hover over or click-auto-copy-to-clipboad functionality. 

**Screenshots**
No Right-Click text options like `copy`
![image](https://github.com/jfrog/jfrog-idea-plugin/assets/4295880/0e8e42ec-d48b-4acb-af47-726c25823096)
Can't copy description either:
![image](https://github.com/jfrog/jfrog-idea-plugin/assets/4295880/49895844-b793-4cf9-9531-1ea06afbb3fb)
Or Xray ID 
![image](https://github.com/jfrog/jfrog-idea-plugin/assets/4295880/31a889c4-2eea-44d5-9900-f25d1f5368e9)

**Versions**
- JFrog IDEA plugin version: org.jfrog.idea (2.2.5)
- Operating system:  macOS 13.3.1
- Xray version: 3.65.2
![image](https://github.com/jfrog/jfrog-idea-plugin/assets/4295880/f6d3aa29-d485-4fd1-9513-7afe3e1b6be9)

**Additional context**
IntelliJ IDEA 2023.1.2 (Ultimate Edition) Build #IU-231.9011.34, built on May 16, 2023
Runtime version: 17.0.6+10-b829.9 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    awt.file.dialog.enable.filter=false
    ide.experimental.ui=true
    scala.erase.compiler.process.jdk.once=false

Non-Bundled Plugins:
    ideanginx9 (0.1.9)
    com.sburlyaev.terminal.plugin (0.4.6)
    main.kotlin.com.jimschubert.intellij.swaggercodegen (4.3.1-p0)
    com.github.patou.gitmoji (1.12.1)
    org.jetbrains.plugins.go-template (231.8109.91)
    Key Promoter X (2023.1.0)
    com.intellij.ideolog (203.0.30.0)
    com.mnr.java.intellij.idea.plugin.base64helper (2.0.3)
    name.kropp.intellij.makefile (231.8109.91)
    com.intellij.kubernetes (231.9011.4)
    mobi.hsz.idea.gitignore (4.5.0)
    String Manipulation (9.7.1)
    org.sonarlint.idea (8.2.0.68615)
    com.intellij.spring.websocket (231.8770.17)
    com.jetbrains.jax.ws (231.8109.90)
    com.jetbrains.php (231.9011.38)
    io.pivotal.jasmine (1.8)
    com.densebrain.intellij.plugins.groovyconvert (1.0)
    google-java-format (1.16.0.2)
    Pythonid (231.9011.34)
    Dart (231.9065)
    com.github.masooh.intellij.plugin.groovyfier (0.2)
    com.intellij.aspectj (231.8109.90)
    MavenRunHelper (4.23.222.2964.0)
    com.intellij.spring.webflow (231.9011.34)
    net.seesharpsoft.intellij.plugins.csv (3.2.0-231)
    org.jfrog.idea (2.2.5)
    org.intellij.scala (2023.1.18)
    rebase-guru (0.1.1)
    com.tabnine.TabNine (1.0.13)

Kotlin: 231-1.8.21-IJ9011.34

**Comment by talarian1** [comment]
Hi @ranma2913, 
Thanks for reporting this issue and sorry for the inconvenience this issue caused.
We suspect that it might be a bug in the IDEA JCEF utility (as the same plugin version works fine on previous IDEA builds).
I have opened this [issue](https://youtrack.jetbrains.com/issue/IDEA-323525/JCEF-Context-menu-stopped-working-as-well-as-CmdC-functionality) and will update you once we will find a solution.
In the meantime, please notice that the CVE itself can be copied from the left tree view, using `cmd+C`:

<img width="500" alt="Screenshot 2023-06-25 at 12 00 24" src="https://github.com/jfrog/jfrog-idea-plugin/assets/24526180/ffdb43ce-71ee-48d0-836b-d14cddf25353">

**Comment by ranma2913** [comment]
Thanks I'll try the left-hand tree. Mainly the CVE I'd is what I'm used to copying so that may be a fine work around while it works as expected.

**Comment by talarian1** [comment]
Hi @ranma2913, It seems like the bug in the IDEA JCEF utility was fixed, as I was able to use `cmd+c ` to copy text from the plugin's screens. Please let me know if you still have problems when using our plugin with the latest version of IntelliJ IDEA.

**Comment by ranma2913** [comment]
Good morning. I'm on different versions now.

My Intellij & Plugin info is as follows:
```
IntelliJ IDEA 2023.2.2 (Ultimate Edition)
Build #IU-232.9921.47, built on September 12, 2023
Licensed to ********
Subscription is active until ********.
Runtime version: 17.0.8+7-b1000.22 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.5
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    awt.file.dialog.enable.filter=false
    ide.experimental.ui=true
    scala.erase.compiler.process.jdk.once=false

Non-Bundled Plugins:
    com.github.patou.gitmoji (1.13.0)
    com.mnr.java.intellij.idea.plugin.base64helper (2.0.3)
    main.kotlin.com.jimschubert.intellij.swaggercodegen (4.3.1-p0)
    org.jetbrains.plugins.go-template (232.9921.62)
    fantom.codeowners (0.6.0)
    com.intellij.ideolog (222.1.0.0)
    com.sburlyaev.terminal.plugin (0.5.2)
    name.kropp.intellij.makefile (232.8660.88)
    Key Promoter X (2023.2.0)
    com.tabnine.TabNine (1.6.0)
    com.intellij.kubernetes (232.9921.28)
    com.intellij.nativeDebug (232.9921.28)
    google-java-format (1.17.0.0)
    com.jetbrains.jax.ws (232.8660.142)
    com.intellij.spring.websocket (232.8660.142)
    String Manipulation (9.11.3)
    com.intellij.spring.webflow (232.9921.47)
    com.intellij.aqua (232.9921.28)
    com.github.masooh.intellij.plugin.groovyfier (0.2)
    com.intellij.aspectj (232.8660.142)
    Dart (232.9559.10)
    net.seesharpsoft.intellij.plugins.csv (3.2.1-232)
    rebase-guru (0.1.1)
    io.pivotal.jasmine (1.8)
    com.intellij.lang.jsgraphql (4.0.2)
    io.flutter (75.1.4)
    org.intellij.scala (2023.2.23)
    MavenRunHelper (4.26.0-IJ2022.2)
    Pythonid (232.9921.47)
    org.jfrog.idea (2.5.1)
    com.intellij.bigdatatools.core (232.9921.47)
    com.intellij.bigdatatools.kafka (232.9921.47)
    com.intellij.bigdatatools.binary.files (232.8660.206)
    com.intellij.bigdatatools.rfs (232.9921.47)
    org.sonarlint.idea (9.0.0.75308)
    mobi.hsz.idea.gitignore (4.5.1)
    com.densebrain.intellij.plugins.groovyconvert (1.0)
    com.jetbrains.php (232.9921.55)

Kotlin: 232-1.9.0-IJ9921.47
```

With these versions:

I CAN `cmd+c` copy from the Vulnerability Title in the Details box.
![image](https://github.com/jfrog/jfrog-idea-plugin/assets/4295880/d10bdd33-1dbb-4f84-be6e-8f906f44d869)

I CAN also select a vulerability ID from the list & `cmd+c` copy the ID from the left hand column.
![image](https://github.com/jfrog/jfrog-idea-plugin/assets/4295880/bd77d704-41c2-40ec-9d92-a3cc1ac279f4)


NOTE: In nether location is there an OS right-click context menu with a Copy option like when highlighting/copying any other text in MacOS (Most Apps). Not sure if this should keep the issue open since there's now a work-around (select/highlight & `cmd+c`).
![image](https://github.com/jfrog/jfrog-idea-plugin/assets/4295880/c52ad14c-8e8a-4b61-bcef-289e100eab92)

**Comment by talarian1** [comment]
Thanks for your detailed response.
I'm closing this issue for now as the `cmd+c` functionality is working.
