### ISSUE TITLE
Vulnerability details unavailable in current version, previously displayed

### ISSUE THREAD

**Issue by vipulasri** [jfrog/jfrog-idea-plugin#462]
**Describe the bug**
The plugin doesn't shows vulnerability details other than just listing the vulnerability titles

**To Reproduce**
1. Scan the project 
2. Observe the list of vulnerabilities inside the dependencies 
3. Click on the vulnerability name and observe nothing pops-up in the right pane

**Expected behavior**
Clicking on vulnerability name should ideally display the details about the vulnerability, as previously it used to work. 

**Screenshots**
<img width="1647" alt="Screenshot 2023-12-28 at 3 52 03 PM" src="https://github.com/jfrog/jfrog-idea-plugin/assets/7822179/9aceabc0-0605-4136-8daf-01b09f7a6f70">

**Versions**
- JFrog IDEA plugin version: 2.6.6
- Operating system: MacOS Sonoma 14.2.1
- Android Studio version: Android Studio Hedgehog | 2023.1.1

**Comment by asafgabai** [comment]
Hey @vipulasri,
Thank you for flagging this issue. We've traced it to JCEF (Java Chromium Embedded Framework) instability in Android Studio 2023.1. This impacts various plugins, including those bundled with Android Studio, relying on JCEF functionality.
While we investigate and work on a fix, you might consider reverting to Android Studio 2022.3, where JCEF appears stable.
We recognize this workaround isn't ideal and are actively addressing the problem in our plugin. Additionally, we've [opened an issue](https://issuetracker.google.com/issues/318179171) with the Android Studio team.
We'll provide updates on our progress here.

**Comment by vipulasri** [comment]
The feature is working fine on the latest version of Android Studio
