### ISSUE TITLE
Attempting to install JFrog Plugin

### ISSUE THREAD

**Issue by kutran** [jfrog/jfrog-idea-plugin#55]
I have Android Studio 3.6.2 and trying to install JFrog Idea Plugin 1.5.0.
- first of all, can't find the plugin in the Marketplace
- when installing by disk, it gives the following message:
   > Plugin Error
   > Problems found loading plugins:
  > Plugin "JFrog" was not loaded: required plugin "org.jetbrains.idea.maven"

**Comment by eyalbe4** [comment]
@kutran,
I'm not sure the JFrog IDEA Plugin is compatible with Android Studio. That's probably the reason why you couldn't find it on the Marketplace and got this error when attempting to install it from disk.

**Comment by kutran** [comment]
Isn't Android Studio just a modified version of IntelliJ IDE?

**Comment by eyalbe4** [comment]
It may be so @kutran, but the plugin has been tested only with IntelliJ IDEA. Looking forward,  we do want to support Android Studio, either by this plugin or a new one.

**Comment by a1flecke** [comment]
@eyalbe4   Is this the best issue to follow for updates on Android Studio support for this plugin?  We would like to have XRay support in Android Studio as well.

**Comment by eyalbe4** [comment]
Sure @a1flecke,
Support for Android Studio is part of our roadmap. We'll update this issue when we have more details to share.

**Comment by OwenMoriarty-JNJ** [comment]
Any update on the  support for Android Studio please?

**Comment by yahavi** [comment]
@OwenMoriarty-JNJ,
We are working on adding Android Studio and Gradle-Kotlin DSL support.
Here are the relevant pull requests:
https://github.com/jfrog/ide-plugins-common/pull/36
https://github.com/jfrog/jfrog-idea-plugin/pull/127

**Comment by yahavi** [comment]
@kutran @a1flecke @OwenMoriarty-JNJ,
JFrog IDEA plugin 1.9.0 is released. This version includes support for Android Studio and Kotlin DSL.
Feel free to download and experience with it.
We'd appreciate your feedback on that.
