### ISSUE TITLE
"Could not connect to Xray: Connection refused: connect" behind corporate firewall

### ISSUE THREAD

**Issue by seanf** [jfrog/jfrog-idea-plugin#73]
**Describe the bug**
Plugin can't connect to Xray. 

**To Reproduce**
1. Configure Xray URL, username (email) and API key (from Artifactory profile page)
2. Click "Test connection"

**Expected behaviour**
Expected a successful connection to Xray, but got the error message "Could not connect to Xray: Connection refused: connect"

**Screenshots**
![image](https://user-images.githubusercontent.com/54155/84892731-724cfe00-b0e1-11ea-952c-72264b78b791.png)
![image](https://user-images.githubusercontent.com/54155/84894195-c0fb9780-b0e3-11ea-95df-4f8e07ebb3b9.png)

**Versions**
- JFrog IDEA plugin version: 1.6.0
- Operating system: Windows 10 Pro 1909
- Xray version: unknown, but it is hosted on jfrog.io

**Additional context**

- The Xray instance uses SAML for SSO, which is why I have to use an API key (https://github.com/jfrog/jfrog-idea-plugin/issues/2#issuecomment-364867815).
- From the error message, I suspect the plugin is failing to use IntelliJ's configured HTTP proxy (with "auto-detect proxy settings").

**Comment by seanf** [comment]
It works if I use manual proxy settings; it's just the auto proxy configuration which the plugin can't handle:

![image](https://user-images.githubusercontent.com/54155/84980918-ac1c1400-b176-11ea-90b8-0bcb10c99092.png)


(I also had to switch from email address to domain user name to avoid a 401.)

**Comment by seanf** [comment]
It looks like the code assumes that there is a single proxy host/port regardless of URL, which I understand isn't true in general with PAC files:

https://github.com/jfrog/jfrog-idea-plugin/blob/5458664b6453efaa6009dd3db14206d065d14785/src/main/java/com/jfrog/ide/idea/configuration/XrayServerConfigImpl.java#L170-L183

**Comment by yahavi** [comment]
Thanks for reporting this issue, @seanf!
We appreciate your help on finding the root cause of the problem in the code.

We love code contribution from the community. 
Would you like to help us to fix this issue quickly by contributing a fix in a pull request? You can find in the [README](https://github.com/jfrog/jfrog-idea-plugin#jfrog-idea-plugin) all necessary steps on how to develop the plugin code.

**Comment by yahavi** [comment]
@seanf, 
JFrog IDEA plugin 1.7.0 is released. 
This versions includes support for providing PAC files from Intellij IDEA configuration. As usual, you can define `Auto-detect proxy settings` as instructed here: https://www.jetbrains.com/help/idea/settings-http-proxy.html.
We'll appreciate your feedback for that.

**Comment by seanf** [comment]
Yes, it's now working both with manual and auto-detect proxy settings. Thanks!
