### ISSUE TITLE
Ability to filter using project dependency or Dev dependency

### ISSUE THREAD

**Issue by andreykishtov** [jfrog/jfrog-idea-plugin#80]
**Is your feature request related to a problem? Please describe.**
I would like to be able to see which vulnerabilities that are important to building the project
and filter out dev dependencies.

**Describe the solution you'd like to see**
I want to see checkbox dependencies and checkbox dev dependencies.

**Comment by eyalbe4** [comment]
Thanks for sharing this feature request @andreykishtov!
Very useful functionality indeed. We'll add this to the plugin's roadmap.

**Comment by yahavi** [comment]
@andreykishtov 1.7.0 is out. This version includes filtering by scope.
