### ISSUE TITLE
General usability suggestions

### ISSUE THREAD

**Issue by yuvalreches** [jfrog/jfrog-idea-plugin#85]
Hey guys :)
Few small yet important things I stumbled upon when using the plugin:
1. When no Xray server configured, the line `To Start using the JFrog Plugin, pleaseconfigure your JFrog Xray details` is missing a comma between `please` and `configure` link
2. When setting up the Xray URL, the first idea that comes to mind if to set the domain, i.e http://myartifactory.ac.me
However, that would result in `HTTP 404`.
I think an example URL should be added below the URL text input, saying `add /xray as a suffix to your Artifactory platform URL`
3. When setting a wrong URL, the error is cut, and the text is not fully shown (it should be wrapped inside the window itself)

**Comment by yahavi** [comment]
Thanks for your valuable feedback, Yuval.
We will fix them all. The first one is fixed in today's release (1.6.2) by https://github.com/jfrog/jfrog-idea-plugin/commit/c03769bca5b5172cce2be6645ceaa9cd8c3804f2.

**Comment by yahavi** [comment]
@yuvalreches fixes for 2 and 3 are in 1.7.0. We'll appreciate your feedback for this!
