### ISSUE TITLE
The go.mod dependencies scan is inaccurate when replace() exists

### ISSUE THREAD

**Issue by yuvalreches** [jfrog/jfrog-idea-plugin#86]
The plugin displays only component versions in the `require(..)` part of the `go.mod` file.
However, when a `replace(..)` section exists in the `go.mod` file, those versions are ignored.

This is quite problematic, as the `replace` part is the actual package to be included in the final build, and if we can't see violation for those we might miss the point, don't we? :)

**Comment by yahavi** [comment]
Should be resolved by https://github.com/jfrog/ide-plugins-common/pull/45 and will be available in the next release.
