### ISSUE TITLE
Xray Scan Produces No Results

### ISSUE THREAD

**Issue by btyler97** [jfrog/jfrog-idea-plugin#97]
Scanning does not appear to be working at all. No scan occurs upon initially opening the project (not sure if that is expected behavior), so I clicked the "refresh" icon to force an Xray scan. The scan runs very quickly (too quickly I would say for the size of the project and number of libraries) and produces no results.

**To Reproduce**
1. Install the JFrog Xray plugin from the Marketplace
2. Restart IntelliJ
3. Configure JFrog Xray connection
4. Open an existing Java/Maven project
5. Click the "Refresh Scan" icon in the JFrog pane

**Expected behavior**
In an earlier version of the plugin and an earlier version of the IDE, I received a detailed list of components with an icon indicating issue severities. I would expect the same with this version, but I don't even get a list of components.

**Screenshots**
Not applicable

**Versions**
- JFrog IDEA plugin version: 1.7.0
- Operating system: MacOS 10.15.7
- Xray version: Cloud
- IntelliJ: 2020.2.3 Ultimate Edition

**Additional context**
We use the cloud hosted Artifactory and X-Ray.

The only logging that occurs is a warning like the following:

`2020-11-04 19:18:05,661 [1400336]   WARN - .AbstractProgressIndicatorBase - This progress indicator is indeterminate, this may lead to visual inconsistency. Please call setIndeterminate(false) before you start progress.
com.jfrog.ide.idea.log.ProgressIndicatorImpl.setFraction(ProgressIndicatorImpl.java:19) `

**Comment by yahavi** [comment]
Thanks for reporting this issue, @btyler97!
Before we start digging into this, we'd like to know whether your environment is well configured.

**A little background** 
To get the best performance, the JFrog Idea plugin extracts the dependencies structure information from the Intellij Maven plugin. Using this methodology, the scan is much faster and less expensive in CPU and network resources.
Therefore the first thing to check is whether the Maven project is loaded properly. Once the Maven project is loaded properly, the plugin can extract the dependencies information from the Maven plugin.
Regardless, if all preconditions are met, the JFrog Idea plugin should work smoothly and automatically.

**Check if your Maven project is properly loaded**
This is how you can check if your Maven project is loaded properly:
1. Open you `pom.xml` and make sure that your pom file does not contains any compilation error. If there are, please fix the errors and wait for Intellij Idea indexing before triggering an Xray scan.
2. Open a Java file and make sure Intellij does not pop up any notification about missing JDK. In case it is the issue, you'll have to provide it with your JDK.
3. Open the `Maven` tab from the right side of the screen and make sure you see your Maven project as well as the project dependencies tree:
![image](https://user-images.githubusercontent.com/11367982/98397191-a2347800-2067-11eb-8fcc-337d0218f628.png)
These dependencies trees are the data sources of the JFrog Idea plugin, therefore it is important to have them.
4. Open the event log and make sure that you don't see any Intellij indexing errors.

If the project is not properly loaded, you can try to restart your Intellij Idea window and try again.
In my example I used the [Maven example](https://github.com/jfrog/project-examples/tree/master/maven-example) in our [Project examples](https://github.com/jfrog/project-examples.git) GitHub repository. Can you please check if you can load and scan this example also?

Please let me know if this information help.

**Comment by btyler97** [comment]
@yahavi, thank you! I'm a little embarrassed that I didn't realize that. You are correct, I had an issue in my `pom.xml` that was causing it to fail compilation (an unresolved property). Once I fixed that issue the scanning started working.

**Comment by barudisshu** [comment]
I have the same issue, and I figure out that intellij idea doesn't recognize maven.config variable at all,
